const systems=[
 {name:'Sun',type:'G2V',distance:'0 ly',distanceLy:0,lum:'1.00',app:'−26.74',temp:'5,772 K',radius:'1.00 R☉',ra:'00h 00m 00s',dec:'00° 00′ 00″'},
 {name:'Sirius A',type:'A1V',distance:'8.60 ly',distanceLy:8.6,lum:'25.4',app:'−1.46',temp:'9,940 K',radius:'1.71 R☉',ra:'06h 45m 09s',dec:'−16° 42′ 58″'},
 {name:'Vega',type:'A0V',distance:'25.04 ly',distanceLy:25.04,lum:'40.12',app:'+0.03',temp:'9,600 K',radius:'2.36 R☉',ra:'18h 36m 56s',dec:'+38° 47′ 01″'},
 {name:'Altair',type:'A7V',distance:'16.80 ly',distanceLy:16.8,lum:'10.6',app:'+0.77',temp:'7,670 K',radius:'1.79 R☉',ra:'19h 50m 47s',dec:'+08° 52′ 06″'},
 {name:'Arcturus',type:'K1.5III',distance:'36.70 ly',distanceLy:36.7,lum:'170',app:'−0.05',temp:'4,286 K',radius:'25.4 R☉',ra:'14h 15m 40s',dec:'+19° 10′ 57″'},
 {name:'Capella',type:'G8III+G0III',distance:'42.90 ly',distanceLy:42.9,lum:'79',app:'+0.08',temp:'5,700 K',radius:'12.2 R☉',ra:'05h 16m 41s',dec:'+45° 59′ 53″'},
 {name:'Betelgeuse',type:'M1-2Ia',distance:'642.5 ly',distanceLy:642.5,lum:'126,000',app:'+0.42',temp:'3,500 K',radius:'900 R☉',ra:'05h 55m 10s',dec:'+07° 24′ 25″'},
 {name:'Rigel',type:'B8Ia',distance:'860 ly',distanceLy:860,lum:'120,000',app:'+0.12',temp:'12,100 K',radius:'74 R☉',ra:'05h 14m 32s',dec:'−08° 12′ 06″'},
 {name:'Deneb',type:'A2Ia',distance:'1,460 ly',distanceLy:1460,lum:'196,000',app:'+1.25',temp:'8,500 K',radius:'203 R☉',ra:'20h 41m 25s',dec:'+45° 16′ 49″'},
 {name:'Eta Carinae',type:'LBV',distance:'7,500 ly',distanceLy:7500,lum:'5,000,000',app:'+1.90',temp:'15,000 K',radius:'~240 R☉',ra:'10h 45m 04s',dec:'−59° 41′ 04″'}
];
const stars=[['Sun',52,51],['Sirius A',79,38],['Vega',46,21],['Altair',15,38],['Arcturus',23,58],['Capella',77,18],['Betelgeuse',86,51],['Rigel',91,62],['Deneb',80,73],['Eta Carinae',30,77],['Procyon',70,76],['Barnard’s Star',41,65],['Tau Ceti',57,72],['Wolf 359',60,35]];
let selected='Vega';
const $=id=>document.getElementById(id);
function solarSignal(distanceLy){if(distanceLy===0)return {irr:'1361 W/m²',lux:'~100,000 lux',mag:'−26.74'};const auPerLy=63241.077;const au=distanceLy*auPerLy;const irr=1361/(au*au);const lux=irr*93;const mag=-26.74+5*Math.log10(au);return {irr:`${irr.toExponential(3)} W/m²`,lux:`${lux.toExponential(3)} lux`,mag:(mag>=0?'+':'')+mag.toFixed(2)};}
function selectSystem(name){selected=name;const s=systems.find(x=>x.name===name)||systems[2];const sig=solarSignal(s.distanceLy);$('selectedName').textContent=s.name.toUpperCase();$('selectedType').textContent=`${s.name==='Vega'?'Alpha Lyrae · ':''}${s.type} · ${s.name==='Arcturus'||s.name==='Betelgeuse'||s.name==='Rigel'||s.name==='Deneb'||s.name==='Eta Carinae'?'Luminous / evolved':'Main Sequence'}`;$('basicData').innerHTML=`<dt>RA / DEC (J2000)</dt><dd>${s.ra} / ${s.dec}</dd><dt>Distance</dt><dd>${s.distance}</dd><dt>Luminosity (L☉)</dt><dd>${s.lum}</dd><dt>Temperature</dt><dd>${s.temp}</dd><dt>Radius</dt><dd>${s.radius}</dd><dt>Spectral Type</dt><dd>${s.type}</dd><dt>Position State</dt><dd>CATALOGUE-DERIVED</dd>`;$('irradiance').textContent=sig.irr;$('lux').textContent=sig.lux;$('sunMag').textContent=sig.mag;$('viewMag').textContent=sig.mag;$('viewLux').textContent=sig.lux;$('uncertainty').textContent='Distance + spectral model dependent';$('marbleId').textContent='MBL-'+Math.abs(hash(name)).toString(16).toUpperCase().padStart(12,'0').slice(0,4)+'-'+Math.abs(hash(name+'a')).toString(16).toUpperCase().slice(0,4)+'-'+Math.abs(hash(name+'b')).toString(16).toUpperCase().slice(0,4);$('selectionHint').textContent=`SELECTED · ${s.name.toUpperCase()}`;document.querySelectorAll('.star,.systems-card tr').forEach(el=>el.classList.toggle('selected',el.dataset.name===name));$('marbleJson').textContent=JSON.stringify({system:s.name,source:'Sun',distance_ly:s.distanceLy,irradiance_W_m2:Number((s.distanceLy?solarSignal(s.distanceLy).irr.replace(' W/m²',''):'1361')),illuminance_lux:s.distanceLy?Number(solarSignal(s.distanceLy).lux.replace(' lux','')):100000,apparent_magnitude:sig.mag,status:'MODELLED',method:'inverse_square + spectral weighting',provenance:'CHRONONAV-STELLAR-1',marble_version:'v2'},null,2);}
function hash(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function renderStars(){const layer=$('starLayer');stars.forEach(([name,x,y],i)=>{const el=document.createElement('button');el.className='star';el.dataset.name=name;el.title=name;el.style.left=`${x}%`;el.style.top=`${y}%`;el.style.transform=`scale(${0.7+(i%4)*.15})`;el.addEventListener('click',()=>selectSystem(name));layer.appendChild(el)});}
function renderTable(){const body=$('systemsTable');body.innerHTML=systems.map(s=>`<tr data-name="${s.name}"><td>${s.name}</td><td>${s.type}</td><td>${s.distance}</td><td>${s.lum}</td><td>${s.app}</td><td>CATALOGUED</td></tr>`).join('');body.querySelectorAll('tr').forEach(r=>r.addEventListener('click',()=>selectSystem(r.dataset.name)));$('systemCount').textContent=`${systems.length} SYSTEMS`;$('cataloguedCount').textContent=systems.length;$('modelledCount').textContent=systems.length;}
function renderSignals(){const max=Math.max(...systems.map(s=>Math.max(1,parseFloat(s.lum.replace(/,/g,''))));const items=[['Sun (Earth)',100000],['Moon (Earth)',0.1],['Sirius (Earth)',0.001],['Vega (Earth)',0.0007],['Sun (Vega)',5e-8],['Sun (Proxima Centauri)',1.7e-9],['Sun (Tau Ceti)',8.4e-10],['Sun (Barnard’s Star)',6.2e-10],['Sun (Wolf 359)',3.1e-10]];$('signalBars').innerHTML=items.map(([label,v])=>{const width=Math.max(3,Math.min(100,50+10*Math.log10(Math.max(v,1e-12)/1e-8)));return `<div class="signal-row"><label>${label}</label><div class="bar"><i style="width:${width}%"></i></div><b>${formatSci(v)}</b></div>`}).join('')}
function formatSci(v){if(v>=1)return v.toLocaleString(undefined,{maximumFractionDigits:1});return v.toExponential(1).replace('e-0','e-').replace('e+0','e+')}
function clock(){const d=new Date();$('clock').textContent=d.toISOString().replace('.000','').replace('T',' ').slice(0,20)+'Z'}
renderStars();renderTable();renderSignals();selectSystem('Vega');clock();setInterval(clock,1000);
document.querySelectorAll('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$('selectionHint').textContent=`VIEW · ${btn.dataset.view.toUpperCase()}`;}));
document.querySelectorAll('.tabs button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');}));
