/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AokRouteImport } from './routes/aok'
import { Route as AuraRouteImport } from './routes/aura'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as MarblesRouteImport } from './routes/marbles'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as RefineryRouteImport } from './routes/refinery'
import { Route as ShadowRouteImport } from './routes/shadow'
import { Route as SourceRouteImport } from './routes/source'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AokRoute = AokRouteImport.update({
  id: '/aok',
  path: '/aok',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraRoute = AuraRouteImport.update({
  id: '/aura',
  path: '/aura',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const MarblesRoute = MarblesRouteImport.update({
  id: '/marbles',
  path: '/marbles',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const RefineryRoute = RefineryRouteImport.update({
  id: '/refinery',
  path: '/refinery',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadowRoute = ShadowRouteImport.update({
  id: '/shadow',
  path: '/shadow',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceRoute = SourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aok': typeof AokRoute
  '/aura': typeof AuraRoute
  '/evidence': typeof EvidenceRoute
  '/marbles': typeof MarblesRoute
  '/pilot': typeof PilotRoute
  '/refinery': typeof RefineryRoute
  '/shadow': typeof ShadowRoute
  '/source': typeof SourceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aok': typeof AokRoute
  '/aura': typeof AuraRoute
  '/evidence': typeof EvidenceRoute
  '/marbles': typeof MarblesRoute
  '/pilot': typeof PilotRoute
  '/refinery': typeof RefineryRoute
  '/shadow': typeof ShadowRoute
  '/source': typeof SourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aok': typeof AokRoute
  '/aura': typeof AuraRoute
  '/evidence': typeof EvidenceRoute
  '/marbles': typeof MarblesRoute
  '/pilot': typeof PilotRoute
  '/refinery': typeof RefineryRoute
  '/shadow': typeof ShadowRoute
  '/source': typeof SourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aok'
    | '/aura'
    | '/evidence'
    | '/marbles'
    | '/pilot'
    | '/refinery'
    | '/shadow'
    | '/source'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aok'
    | '/aura'
    | '/evidence'
    | '/marbles'
    | '/pilot'
    | '/refinery'
    | '/shadow'
    | '/source'
  id:
    | '__root__'
    | '/'
    | '/aok'
    | '/aura'
    | '/evidence'
    | '/marbles'
    | '/pilot'
    | '/refinery'
    | '/shadow'
    | '/source'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AokRoute: typeof AokRoute
  AuraRoute: typeof AuraRoute
  EvidenceRoute: typeof EvidenceRoute
  MarblesRoute: typeof MarblesRoute
  PilotRoute: typeof PilotRoute
  RefineryRoute: typeof RefineryRoute
  ShadowRoute: typeof ShadowRoute
  SourceRoute: typeof SourceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aok': {
      id: '/aok'
      path: '/aok'
      fullPath: '/aok'
      preLoaderRoute: typeof AokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura': {
      id: '/aura'
      path: '/aura'
      fullPath: '/aura'
      preLoaderRoute: typeof AuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marbles': {
      id: '/marbles'
      path: '/marbles'
      fullPath: '/marbles'
      preLoaderRoute: typeof MarblesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refinery': {
      id: '/refinery'
      path: '/refinery'
      fullPath: '/refinery'
      preLoaderRoute: typeof RefineryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shadow': {
      id: '/shadow'
      path: '/shadow'
      fullPath: '/shadow'
      preLoaderRoute: typeof ShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source': {
      id: '/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof SourceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AokRoute: AokRoute,
  AuraRoute: AuraRoute,
  EvidenceRoute: EvidenceRoute,
  MarblesRoute: MarblesRoute,
  PilotRoute: PilotRoute,
  RefineryRoute: RefineryRoute,
  ShadowRoute: ShadowRoute,
  SourceRoute: SourceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
